#!/usr/bin/env python

import irank
from irank import rhythmbox
import sys
import os
import subprocess

def run_with_current_track(process_name):
	subprocess.Popen([process_name, rhythmbox.current_file()]).communicate()

def edit_loop():
	while True:
		input = None
		try:
			input = raw_input().strip()
		except EOFError: break
		if input == 'd':
			run_with_current_track('irank-delete')
		elif input == 'k':
			run_with_current_track('irank-keep')
		elif input == 'a':
			run_with_current_track('irank-discard')
		elif not input:
			clear()
			# just running the function should work, but curses gets in a funny state sometimes...
			run_with_current_track('irank-edit')
			display_song(rhythmbox.current_file())

def clear():
	os.system("clear")

def display_song(current_song):
	clear()
	if not current_song: return
	print (os.path.basename(current_song))
	print
	try:
		print irank.Song(current_song).values
	except StandardError, e:
		print e

def display_loop():
	def on_song(path):
		current_song = path
		display_song(current_song)
	rhythmbox.playing_songs(on_song)

if __name__ == '__main__':
	args = sys.argv[1:]
	actions = {'edit': edit_loop,'display': display_loop}
	if len(args) != 1 or args[0] not in actions:
		print "Usage: %s [%s]" % (os.path.basename(sys.argv[0]), '|'.join(actions))
		sys.exit(1)
	try:
		actions[args[0]]()
		sys.exit(0)
	except KeyboardInterrupt:
		sys.exit(2)




