#!/usr/bin/env python
import sys

from irank import editor
LS_FLAG = '-l'

if __name__ == '__main__':
	args = sys.argv[1:]
	if LS_FLAG in args:
		args.remove(LS_FLAG)
		editor.LIST_MODE = True
	editor.main(*args)
