#!/usr/bin/env python
import sys
import irank
import optparse

if __name__ == '__main__':
	p = optparse.OptionParser()
	for k in irank.KEYS:
		p.add_option('--' + k, default=None, type='int', dest=k, help='set ' + k)
	opts, files = p.parse_args()
	modifications = {}
	for k in irank.KEYS:
		val = getattr(opts, k)
		if val is not None:
			modifications[k] = val

	assert len(modifications) > 0
	print >> sys.stderr, "Applying modifications: %s to %s files\n\nOK [Y/n]? " % (modifications,len(files))
	if raw_input().strip().lower() not in ('', 'y', 'yes'): sys.exit(1)

	for file in files:
		song = irank.Song(file)
		for key, val in modifications.items():
			song[key] = val
		song.save()
