#!/usr/bin/env python

import irank
from irank import mpris
import sys
import os
import subprocess

player = mpris.Player()

def run_with_current_track(process_name, next_song=False):
	subprocess.check_call([process_name, player.track])
	if(next_song):
		player.next()

def edit_loop():
	while True:
		input = None
		try:
			input = raw_input().strip()
		except EOFError: break
		if input == 'd':
			run_with_current_track('irank-delete', False)
		elif input == 'k':
			run_with_current_track('irank-keep', True)
		elif input in ('a','y'):
			run_with_current_track('irank-discard', True)
		elif not input:
			clear()
			# just running the function should work, but curses gets in a funny state sometimes...
			run_with_current_track('irank-edit', False)
			display_song(player.track)

def clear():
	os.system("clear")

def display_song(current_song):
	clear()
	if not current_song: return
	print (os.path.basename(current_song))
	print
	try:
		print irank.Song(current_song).values
	except StandardError, e:
		print e

def display_loop():
	player.each_track(display_song)

if __name__ == '__main__':
	args = sys.argv[1:]
	actions = {'edit': edit_loop,'display': display_loop}
	if len(args) != 1 or args[0] not in actions:
		print "Usage: %s [%s]" % (os.path.basename(sys.argv[0]), '|'.join(actions))
		sys.exit(1)
	try:
		actions[args[0]]()
		sys.exit(0)
	except subprocess.CalledProcessError, e:
		print >> sys.stderr, e
		sys.exit(1)
	except KeyboardInterrupt:
		sys.exit(2)

